### ISSUE TITLE
The mongo driver is required in order to build GridFs.

### ISSUE THREAD

**Issue by dipenpatel235** [28msec/gridfs-fuse#11]
CMake Error at CMakeLists.txt:51 (MESSAGE):
  The mongo driver is required in order to build GridFs.

**Comment by dipenpatel235** [comment]
for centos ned to install dependancy using below command
yum install mongo-c*

**Comment by diman82** [comment]
@dipenpatel235 I still get this message, even though I've installed "sudo yum install mongo-c*"
